version: '3.8'
services:
  mysqlDB:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?error}
      MYSQL_USER: ${DB_USER:?error}
      MYSQL_PASSWORD: ${DB_PASSWORD:?error}
      MYSQL_DATABASE: ${DB_NAME:?error}
    ports:
      - "3308:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_ARBITRARY: 1
      # should be identical with mysql service name 
      # and also this is server name
      PMA_HOST: mysqlDB
      PMA_PORT: 3306
      # it will be use for auto login
      # PMA_USER: ${DB_USER:?error}
      # PMA_PASSWORD: ${DB_PASSWORD:?error}

    ports:
      - "18345:80"

volumes:
  mysqlData: