name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: create .env
      run: |
        echo "${{secrets.DB_PASSWORD }}" > .env
        echo "${{secrets.DB_USER }}" > .env
        echo "${{secrets.DB_NAME }}" > .env
        echo "${{secrets.DB_IP }}" > .env
        echo "${{secrets.DB_PORT }}" > .env
    - name: Download Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Get dependencies
      run: |
                go get -v -t -d ./...

    - name: Build
      run: go build .

    - name: Test
      run: go test -v .
